export const Aave = [
	{
        "type":"function",
        "name":"getUserAccountData",
        "inputs":[
            {
                "name":"custodian",
                "type":"address",
                "internalType":"address"
            }
        ],
        "outputs":[
            {
                "name":"collateralUSD",
                "type":"uint256",
                "internalType":"uint256"
            },
            {
                "name":"debtUSD",
                "type":"uint256",
                "internalType":"uint256"
            },
            {
                "name":"canBorrowUSD",
                "type":"uint256",
                "internalType":"uint256"
            },
            {
                "name":"canBorrowUSDC",
                "type":"uint256",
                "internalType":"uint256"
            },
            {
                "name":"_currentLiquidationThreshold",
                "type":"uint256",
                "internalType":"uint256"
            },
            {
                "name":"_ltv",
                "type":"uint256",
                "internalType":"uint256"
            }
        ],
        "stateMutability":"view"
    },
    {
        "type":"function",
        "name":"getHealthFactor",
        "inputs":[
            {
                "name":"custodian",
                "type":"address",
                "internalType":"address"
            }
        ],
        "outputs":[
            {
                "name":"hf",
                "type":"uint256",
                "internalType":"uint256"
            },
            {
                "name":"status",
                "type":"uint8",
                "internalType":"enum HealthStatus"
            }
        ],
        "stateMutability":"view"
    },
    {
        "type":"function",
        "name":"getVariableDebt",
        "inputs":[
            {
                "name":"custodian",
                "type":"address",
                "internalType":"address"
            },
            {
                "name":"asset",
                "type":"address",
                "internalType":"address"
            }
        ],
        "outputs":[
            {
                "name":"",
                "type":"uint256",
                "internalType":"uint256"
            }
        ],
        "stateMutability":"view"
    },
    {
        "type":"function",
        "name":"getSupplyBalance",
        "inputs":[
            {
                "name":"custodian",
                "type":"address",
                "internalType":"address"
            },
            {
                "name":"asset",
                "type":"address",
                "internalType":"address"
            }
        ],
        "outputs":[
            {
                "name":"",
                "type":"uint256",
                "internalType":"uint256"
            }
        ],
        "stateMutability":"view"
    }
] as const
