export const LiquidatorAdapter = [
	{
		"type":"function",
		"name":"getRiskState",
		"inputs":[
			{
				"name":"user",
				"type":"address",
				"internalType":"address"
			}
		],
		"outputs":[
			{
				"name":"rs",
				"type":"tuple",
				"internalType":"struct ILiquidationAdapter.RiskState",
				"components":[
					{
					"name":"liquidatable",
					"type":"bool",
					"internalType":"bool"
					},
					{
					"name":"riskMetric",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"collateralUSD",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"debtUSD",
					"type":"uint256",
					"internalType":"uint256"
					}
				]
			}
		],
		"stateMutability":"nonpayable"
	},
	{
		"type":"function",
		"name":"getLiquidationStatus",
		"inputs":[
			{
				"name":"user",
				"type":"address",
				"internalType":"address"
			},
			{
				"name":"collateralAsset",
				"type":"address",
				"internalType":"address"
			}
		],
		"outputs":[
			{
				"name":"lp",
				"type":"tuple",
				"internalType":"struct ILiquidationAdapter.LiquidationStatus",
				"components":[
					{
					"name":"maxDebtToCover",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"actualReturn",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"expectedReturn",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"expectedProfit",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"liquidationBonus",
					"type":"uint256",
					"internalType":"uint256"
					}
				]
			}
		],
		"stateMutability":"nonpayable"
	}
] as const
