// @desc Include only key events for tracking user position & the getCollateralAmount()

export const LiiBorrowV1 = [
	{
		"type":"function",
		"name":"getUserSuppliedCollateralAmount",
		"inputs":[
			{
				"name":"user",
				"type":"address",
				"internalType":"address"
			}
		],
		"outputs":[
			{
				"name":"userCollateral",
				"type":"tuple[]",
				"internalType":"struct UserCollateral[]",
				"components":[
					{
					"name":"symbol",
					"type":"string",
					"internalType":"string"
					},
					{
					"name":"collateral",
					"type":"address",
					"internalType":"address"
					},
					{
					"name":"amount",
					"type":"uint256",
					"internalType":"uint256"
					},
					{
					"name":"value",
					"type":"uint256",
					"internalType":"uint256"
					}
				]
			}
		],
		"stateMutability":"view"
	},
	{
		"type":"function",
		"name":"getCollateralAmount",
		"inputs":[
			{
				"name":"collateral",
				"type":"address",
				"internalType":"address"
			},
			{
				"name":"valueOfRepayAmount",
				"type":"uint256",
				"internalType":"uint256"
			}
		],
		"outputs":[
			{
				"name":"",
				"type":"uint256",
				"internalType":"uint256"
			}
		],
		"stateMutability":"view"
	}
] as const
